script_key="YrMGlHVZJYWpvtBaeKtZJOAtEBmcQbkQ";
setfpscap(10)

getgenv().sailorPieceConfig = {  
    OPTIMIZATION = true,  -- true = optimize + show ui, false = disable ui
    AUTO_KICK = true,  -- Autokick if no TRADE_ITEM items left
    KICK_IF_NO_TRADE_USERNAME = true,
    TRADE_SEA_1 = true,
    TRADE_USERNAME = { "k1myebo_m799", "Alka3825250", "pgik_jkjytti41", "Sw_bancroft", "lychee_blox6776" },  -- "Username"
    TRADE_ITEM = {        
        "Abyss Sigil",
        "Adamantite",
        "Ancient Fragment",
        "Ancient Shard",
        "Atomic Core",
        "Aura Crate",
        "Azure Heart",
        "Blood Ring",
        "Bloodline Stone",
        "Boss Key",
        "Boss Rush Ticket",
        "Boss Ticket",
        "Broken Sword",
        "Clan Reroll",
        "Corrupt Crown",
        "Cosmetic Crate",
        "Cosmic Essence",
        "Crystal Key",
        "Dark Ring",
        "Diamond",
        "Dismantle Fang",
        "Dominion Brand",
        "Dungeon Key",
        "Dungeon Ticket",
        "Easter Egg",
        "Easter Key",
        "Evolution Fragment",
        "Hōgyoku Fragment",
        "Galaxy Shard",
        "Infinity Essence",
        "Magic Essence",
        "Magic Shard",
        "Mana Core",
        "Monster Pulse",
        "Mythical Chest",
        "Mythril",
        "Obsidian",
        "Passive Shard",
        "Path Fragment",
        "Phantasm Core",
        "Power Fragment",
        "Power Shard",
        "Race Reroll",
        "Reiatsu Core",
        "Relic Part #1",
        "Relic Part #2",
        "Relic Part #3",
        "Relic Part #4",
        "Relic Part #5",
        "Relic Part #6",
        "Relic Part #7",
        "Relic Part #8",
        "Rush Key",
        "Secret Chest",
        "Soul Flame",
        "Slime Core",
        "Spell Echo",
        "Star Mark",
        "Time Remnant",
        "Tower Key",
        "Trait Reroll",
        "Upper Seal",
        "Vampire Omen",
        "Void Fragment",
        "Wood",
        "World Core",
    },

    WEBHOOK_URL = "https://discord.com/api/webhooks/1498122446732001282/V24aQC79oRA5-Dff2gYXyk3S6O5f79xDBojoxu_g3p0gnV8rijSzoaw6vgY5Yac6TKvu",
    DISCORD_ID = "285071154300059648",
    WEBHOOK_NOTE = "",
    SHOW_WEBHOOK_USERNAME = true,
    SHOW_WEBHOOK_JOBID = false,
}

loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/eb9a467b35fe098d20677eb16ec559a4.lua"))()
