script_key="YrMGlHVZJYWpvtBaeKtZJOAtEBmcQbkQ";
setfpscap(10)

getgenv().sailorPieceConfig = {  
    AUTO_UPDATE_RESTART = true,
    
    MULTI_FARM = { "ArenaFighter", "Ninja", "Swordsman", "AcademyTeacher", "Slime", "Curse", "StrongSorcerer" },  -- Instant tp kill npc
    DO_REPEATABLE_QUEST = "QuestNPC19",
    AUTO_FARM = { "Jinwoo Boss", "Alucard Boss", "Yuji Boss", "Gojo Boss", "Sukuna Boss", "Anos Boss", "Aizen Boss", "Strongest of Today Boss", "Strongest in History Boss", "Rimuru Boss", "Saber Boss", "QinShi Boss", "Ichigo Boss", "Ice Queen Boss" },  
    
    SUMMON_BOSS = { "Ichigo", "Qin Shi", "Saber", "Moon Slayer Normal", "Ice Queen Normal", "Blessed Maiden Normal" },
    EQUIP_WEAPON = {"Ice Queen", "Strongest Shinobi", "Moon Slayer", "Saber Alter", "Gilgamesh", "Strongest In History", "Ichigo", "Gryphon", "Dark Blade", "Katana"},
    BUY_WEAPON = {"Katana", "Dark Blade", "Gryphon", "Ichigo", "Strongest In History", "Gilgamesh", "Saber Alter", "Moon Slayer", "Strongest Shinobi", "Ice Queen"},
    BLESS_WEAPON = { 
        ["Ice Queen"] = 10,
        ["Strongest Shinobi"] = 10,
        ["Moon Slayer"] = 10,
        ["Saber Alter"] = 10,
        ["Gilgamesh"] = 10,
        ["Strongest In History"] = 10,
        ["Ichigo"] = 10,
        ["Gryphon"] = 6,
        ["Dark Blade"] = 3 
    },
    STAT_POINT_PERCENTAGE = { 
        ["Sword"] = 90, 
        ["Defense"] = 10,
        ["Melee"] = 0, 
        ["Power"] = 0 
    },
    BUILD_MODE = "Luck",
    USE_ITEM = { "Common Chest", "Rare Chest", "Epic Chest", "Legendary Chest", "Aura Crate (Untradeable)", "Cosmetic Crate (Untradeable)", "Secret Chest (Untradeable)", "Mythical Chest" },
    BUY_MERCHANT = { "Race Reroll", "Trait Reroll", "Clan Reroll", "Passive Shard", "Boss Key", "Dungeon Key", "Rush Key", "Boss Ticket", "Haki Color Reroll", "Common Chest", "Rare Chest", "Epic Chest", "Legendary Chest", "Mythical Chest", "Secret Chest" },

    REROLL_RACE_UNTIL = { "Luckborn" },
    REROLL_CLAN_UNTIL = { "Eminence" },
    REROLL_TRAIT_UNTIL = { "Emperor" },
    REROLL_STAT_UNTIL = { 
        ["Damage"] = "S", 
        ["Defense"] = "S", 
        ["CooldownReduction"] = "S", 
        ["CritChance"] = "S", 
        ["CritDamage"] = "S", 
        ["DamageReduction"] = "S", 
        ["Luck"] = "Z" 
    },
    REROLL_PASSIVE_UNTIL = { 
      ["Ichigo"] = { "Fortune Chosen", "Executioner", "Rampage", "Damage V" }, 
      ["Strongest In History"] = { "Fortune Chosen", "Executioner", "Rampage", "Damage V" },
      ["Gilgamesh"] = { "Fortune Chosen", "Executioner", "Rampage", "Damage V" },
      ["Saber Alter"] = { "Fortune Chosen", "Executioner", "Rampage", "Damage V" },
      ["Moon Slayer"] = { "Fortune Chosen", "Executioner", "Rampage", "Damage V" },
      ["Strongest Shinobi"] = { "Fortune Chosen", "Executioner", "Rampage", "Damage V" },
      ["Ice Queen"] = { "Fortune Chosen", "Executioner", "Rampage", "Damage V" },
    },
    REROLL_POWER_UNTIL = { "Colossus" },
    DELETE_ARTIFACT_RARITY = { "Common" },
    EQUIP_ARTIFACT_SET = "Abyssal Crown",

    -- Autotrade
    TRADE_USERNAME = { "trdacc654321" },
    TRADE_ITEM = {
        "Abyss Edge",
        "Abyss Sigil",
        "Alter Essence",
        "Ancient Shard",
        "Atomic Core",
        "Atomic Omen",
        "Aura Crate",
        "Azure Heart",
        "Battle Shard",
        "Battle Sigil",
        "Blood Ring",
        "Boss Key",
        "Boss Rush Ticket",
        "Boss Ticket",
        "Broken Sword",
        "Calamity Seal",
        "Chrysalis Sigil",
        "Clan Reroll",
        "Corrupt Crown",
        "Corruption Core",
        "Cosmetic Crate",
        "Crescent Shard",
        "Crimson Heart",
        "Cursed Finger",
        "Cursed Flesh",
        "Dark Grail",
        "Dark Ring",
        "Demon Remnant",
        "Dismantle Fang",
        "Divine Grail",
        "Dungeon Key",
        "Dungeon Ticket",
        "Eminence Essence",
        "Eternal Core",
        "Evolution Fragment",
        "Frost Brand",
        "Frost Relic",
        "Frozen Brand",
        "Frozen Will",
        "Fusion Ring",
        "Gale Essence",
        "Glacier Remnant",
        "Golden Essence",
        "Haki Color Reroll",
        "Hog Fragment",
        "Hogyoku Frag",
        "Ice Core",
        "Illusion Prism",
        "Imperial Seal",
        "Infinity Essence",
        "Jade Tablet",
        "Kamish Dagger",
        "Limitless Ring",
        "Lunar Essence",
        "Magic Shard",
        "Mirage Pendant",
        "Monarch Core",
        "Monarch Essence",
        "Moon Crest",
        "Morgan Remnant",
        "Mythical Chest",
        "Passive Shard",
        "Path Fragment",
        "Phantasm Core",
        "Power Remnant",
        "Power Shard",
        "Race Reroll",
        "Reiatsu Core",
        "Rush Key",
        "Secret Chest",
        "Shadow Crystal",
        "Shadow Heart",
        "Shadow Remnant",
        "Soul Flame",
        "Soul Fragment",
        "Spiritual Core",
        "Silent Storm",
        "Slime Core",
        "Soul Flame",
        "Tempest Relic",
        "Throne Remnant",
        "Tide Remnant",
        "Tower Key",
        "Transcendent Core",
        "Trait Reroll",
        "Umbral Capsule",
        "Upper Seal",
        "Void Fragment",
        "Void Seed",
        "Worthiness Fragment",
        "Yamato Essence",
},
    -- Discord
    WEBHOOK_ITEM_NAME = { "Aura Crate", "Cosmetic Crate" },
    WEBHOOK_URL = "https://discord.com/api/webhooks/1489367505226170430/3W21u4vaWuzWM4Mi7vf9e_jKm_XiTWh9x3GVGAFjqkIKQhErWNd4Ex_ohmoBfE0W1M7w",
    DISCORD_ID = "",
    WEBHOOK_NOTE = "",
    SHOW_PUBLIC_DISCORD_ID = true,
    SHOW_WEBHOOK_USERNAME = true,
    SHOW_WEBHOOK_JOBID = true,
}   

loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/1c7ac2a2f86ecf894218a424a1be7667.lua"))()
