script_key="LTgQkSjr7zrtmwZYm72PU9KuGmGA5BFj6S";
getgenv().SailorPieceConfig = {
    AutoFarm         = true,
    AutoQuest        = true,
    AutoStats        = true,
    AutoBuyWeapons   = true,
    AutoSaber        = true,
    AutoIchigo       = true,
    AutoHaki         = true,
    AutoHogyoku      = true,
    AutoAscend       = true,
    AutoRedeemCodes  = true,
    DisablePvP       = true,
    AutoOpenChest    = true,
    OpenChests       = {
        "Common Chest",
        "Rare Chest",
        "Epic Chest",
        "Legendary Chest",
    },
    AutoBlessing     = true,
    AutoReroll       = true,
    TargetRace       = "Kitsune",
    TargetClan       = "Monarch",
    AutoTraitReroll  = true,
    TargetTraitRarity = "Secret",
    AutoMerchant     = true,
    AutoEquipTitle   = true,
    AutoEquipAccessory = true,
    AutoEquipArtifact = true,
    AutoSkillTree    = true,
    SkillTreePriority = {"Luck", "Damage", "CritChance", "CritDamage", "HP"},
    WebhookURL       = "https://discord.com/api/webhooks/1484989763399323679/RdEkKYN9PC2BskfGrRYnCMLxQksGP185e_uHzdG6EolqCUZKm6grkp5jex6JWeQmjiMy",
    FPSBoost         = true,
    FPSLock          = 15,
    HideMobVFX       = true,
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/1169527463a6fb002d07c345110bc0aa.lua"))()
