script_key="aDgJnOlAuVtVVAGGAjzULYXrBcFtQyHB";
getgenv().AutoTradeConfig = {
    -- Danh sách acc main (display name hoặc username) - hỗ trợ nhiều acc
    MainAccounts = {
        "trdacc654321",
        -- thêm acc main ở đây, ví dụ:
        -- "AccMain2",
        -- "AccMain3",
    },

    -- Danh sách tên item muốn trade (chỉ cần tên, tự detect category + max quantity)
    Items = {
        "Race Reroll",
        "Clan Reroll",
        "Trait Reroll",
        "Haki Color Reroll",
        "Mythical Chest",
        "Secret Chest",
        "Aura Crate",
        "Cosmetic Crate",
        "Infinity Essence",
        "Divine Grail",
        "Throne Remnant",
        "Ancient Shard",
        "Golden Essence",
        "Phantasm Core",
        "Broken Sword",
        "Azure Heart",
        "Silent Storm",
        "Yamato Essence",
        "Frozen Will",
        "Chrysalis Sigil",
        "Evolution Fragment",
        "Transcendent Core",
        "Fusion Ring",
        "Worthiness Fragment",
        "Hogyoku Frag",
        "Mirage Pendant",
        "Illusion Prism",
        "Reiatsu Core",
        "Boss Ticket",
        "Upper Seal",
        "Moon Crest",
        "Crescent Shard",
        "Lunar Essence",
        "Demon Remnant",
        "Abyss Sigil",
        "Atomic Core",
        "Atomic Omen",
        "Eminence Essence",
        "Shadow Remnant",
        "Magic Shard",
        "Void Seed",
        "Rush Key",
        "Umbral Capsule",
        "Dungeon Ticket",
        "Monarch Core",
        "Monarch Essence",
        "Kamish Dagger",
        "Shadow Crystal",
        "Abyss Edge",
        "Dark Ring",
        "Shadow Heart",
        "Dark Grail",
        "Corrupt Crown",
        "Corruption Core",
        "Alter Essence",
        "Morgan Remnant",
        "Cursed Finger",
        "Dismantle Fang",
        "Crimson Heart",
        "Battle Sigil",
        "Path Fragment",
        "Eternal Core",
        "Power Remnant",
        "Tempest Relic",
        "Slime Core",
        "Calamity Seal",
        "Boss Rush Ticket",
        "Dungeon Key",
        "Tower Key",
        "Boss Key",
        "Passive Shard",
        "Power Shard",
        "Imperial Seal",
        "Jade Tablet",
        "Tide Remnant",
        "Gale Essence",
        "Frost Relic",
        "Ice Core", 
        "Frost Brand", 
        "Glacier Remnant", 
        "Battle Shard",
        "Frozen Brand",
    },
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/75c7fe88bf77410a404199a69629aae3.lua"))()
