script_key="aDgJnOlAuVtVVAGGAjzULYXrBcFtQyHB";
getgenv().AutoTradeConfig = {
    MainAccount = "mimabau1904",
    Items = {
        -- [ CATEGORY: REROLLS ] --
        "Race Reroll",
        "Clan Reroll",
        "Trait Reroll",
        "Haki Color Reroll",        
        -- [ CATEGORY: CHESTS & CRATES ] --
        "Mythical Chest",
        "Secret Chest",
        "Aura Crate",
        "Cosmetic Crate",
        -- [ CATEGORY: KEYS & TICKETS ] --
        "Dungeon Ticket",
        "Boss Ticket",
        "Boss Rush Ticket",
        "Dungeon Key",
        "Tower Key",
        "Boss Key",
        "Slime Key",
        "Malevolent Key",
        "Divine Grail",
        "Dark Grail",
        -- [ CATEGORY: SHARDS & SPECIAL MATERIALS ] --
        "Passive Shard",
        "Power Shard",
        "Abyss Sigil",
        "Chrysalis Sigil",
        "Upper Seal",
        "Calamity Seal",
        "Battle Sigil",
        "Cursed Finger",
        "Hogyoku Frag",
        "Atomic Core",
        "Azure Heart",
        "Broken Sword",
        "Tempest Relic",
        "Infinity Essence",
        "Blue Singularity",
        "Reversal Pulse",
        "Energy Shard",
        "Cursed Flesh",
        "Throne Remnant",
        "Ancient Shard",
        "Golden Essence",
        "Phantasm Core",
        "Silent Storm",
        "Yamato Essence",
        "Frozen Will",
        "Worthiness Fragment",
        "Evolution Fragment",
        "Transcendent Core",
        "Imperial Seal",
        "Jade Tablet",
        "Tide Remnant",
        "Gale Essence",
        "Fusion Ring"
    },
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/75c7fe88bf77410a404199a69629aae3.lua"))()
