script_key="aDgJnOlAuVtVVAGGAjzULYXrBcFtQyHB";
getgenv().AutoTradeConfig = {
    -- Danh sách acc main (display name hoặc username) - hỗ trợ nhiều acc
    MainAccounts = {
        "trdacc654321",
        -- thêm acc main ở đây, ví dụ:
        -- "AccMain2",
        -- "AccMain3",
    },

    -- Danh sách tên item muốn trade (chỉ cần tên, tự detect category + max quantity)
    Items = {
        "Abyss Edge",
        "Abyss Sigil",
        "Alter Essence",
        "Ancient Shard",
        "Atomic Core",
        "Atomic Omen",
        "Aura Crate",
        "Azure Heart",
        "Battle Shard",
        "Battle Sigil",
        "Blood Ring",
        "Boss Key",
        "Boss Rush Ticket",
        "Boss Ticket",
        "Broken Sword",
        "Calamity Seal",
        "Chrysalis Sigil",
        "Clan Reroll",
        "Corrupt Crown",
        "Corruption Core",
        "Cosmetic Crate",
        "Crescent Shard",
        "Crimson Heart",
        "Cursed Finger",
        "Cursed Flesh",
        "Dark Grail",
        "Dark Ring",
        "Demon Remnant",
        "Dismantle Fang",
        "Divine Grail",
        "Dungeon Key",
        "Dungeon Ticket",
        "Eminence Essence",
        "Eternal Core",
        "Evolution Fragment",
        "Frost Brand",
        "Frost Relic",
        "Frozen Brand",
        "Frozen Will",
        "Fusion Ring",
        "Gale Essence",
        "Glacier Remnant",
        "Golden Essence",
        "Haki Color Reroll",
        "Hog Fragment",
        "Hogyoku Frag",
        "Ice Core",
        "Illusion Prism",
        "Imperial Seal",
        "Infinity Essence",
        "Jade Tablet",
        "Kamish Dagger",
        "Limitless Ring",
        "Lunar Essence",
        "Magic Shard",
        "Malevolent Key",
        "Mirage Pendant",
        "Monarch Core",
        "Monarch Essence",
        "Moon Crest",
        "Morgan Remnant",
        "Mythical Chest",
        "Passive Shard",
        "Path Fragment",
        "Phantasm Core",
        "Power Remnant",
        "Power Shard",
        "Race Reroll",
        "Reiatsu Core",
        "Rush Key",
        "Secret Chest",
        "Shadow Crystal",
        "Shadow Heart",
        "Shadow Remnant",
        "Silent Storm",
        "Slime Core",
        "Slime Key",
        "Soul Flame",
        "Tempest Relic",
        "Throne Remnant",
        "Tide Remnant",
        "Tower Key",
        "Transcendent Core",
        "Trait Reroll",
        "Umbral Capsule",
        "Upper Seal",
        "Void Fragment",
        "Void Seed",
        "Worthiness Fragment",
        "Yamato Essence",
    },
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/75c7fe88bf77410a404199a69629aae3.lua"))()
